update mime to v3
updating to v4 causes:
```
[11ty] Writing ./dist/site.webmanifest from ./src/site.webmanifest.njk
[11ty] Writing ./dist/assets/scripts/main.js from ./src/assets/scripts/scripts.11ty.js
[11ty] Writing ./dist/assets/styles/main.css from ./src/assets/styles/styles.11ty.js
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble writing to "./dist/index.html" from "./src/index.njk" (via EleventyTemplateError)
[11ty] 2. mime.getType is not a function (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError: mime.getType is not a function
[11ty]     at Context.base64file (/Users/dtreskunov/github/maxboeck-resume/utils/filters.js:39:31)
[11ty]     at Context.<anonymous> (file:///Users/dtreskunov/github/maxboeck-resume/node_modules/@11ty/eleventy/src/UserConfig.js:419:24)
[11ty]     at Context.fn (file:///Users/dtreskunov/github/maxboeck-resume/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:37:23)
[11ty]     at Context.<anonymous> (file:///Users/dtreskunov/github/maxboeck-resume/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:109:15)
[11ty]     at Template.root [as rootRenderFunc] (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:28:61)
[11ty]     at Template.render (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:454:10)
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:19:10)
[11ty]     at fn (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:26:24)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:66:22
[11ty]     at executeSync (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:8:15)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:65:11
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:15:1)
[11ty]     at createTemplate (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:254:9)
[11ty]     at handle (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:265:11)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:276:9
[11ty]     at next (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/lib.js:258:7)
[11ty]     at Object.asyncIter (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/lib.js:263:3)
[11ty]     at Environment.getTemplate (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:259:9)
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:13:5)
[11ty]     at fn (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:26:24)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:66:22
[11ty]     at executeSync (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:8:15)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:65:11
[11ty]     at waterfall (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:71:38)
[11ty]     at Environment.waterfall (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:316:12)
[11ty]     at Template.root [as rootRenderFunc] (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:28:5)
[11ty]     at Template.render (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:454:10)
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:56:10)
[11ty]     at fn (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:26:24)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:66:22
[11ty]     at executeSync (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:8:15)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:65:11
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:52:1)
[11ty]     at createTemplate (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:254:9)
[11ty]     at handle (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:265:11)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:276:9
[11ty]     at next (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/lib.js:258:7)
[11ty]     at Object.asyncIter (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/lib.js:263:3)
[11ty]     at Environment.getTemplate (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:259:9)
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:50:5)
[11ty]     at fn (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:26:24)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:66:22
[11ty]     at executeSync (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:8:15)
[11ty]     at /Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:65:11
[11ty]     at waterfall (/Users/dtreskunov/github/maxboeck-resume/node_modules/a-sync-waterfall/index.js:71:38)
[11ty]     at Environment.waterfall (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:316:12)
[11ty]     at eval (eval at _compile (/Users/dtreskunov/github/maxboeck-resume/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:65:5)
[11ty]     at file:///Users/dtreskunov/github/maxboeck-resume/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:221:8
```